//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        public int Idc { get; set; }
        public Nullable<long> Matricula { get; set; }
        public Nullable<short> Clave { get; set; }
        public Nullable<int> Parcial1 { get; set; }
        public Nullable<int> Parcial2 { get; set; }
        public Nullable<int> parcial3 { get; set; }
    
        public virtual alumnos alumnos { get; set; }
        public virtual docentes docentes { get; set; }
    }
}
